update the prj script

diff --git a/.local/bin/prj b/.local/bin/prj
--- a/.local/bin/prj
+++ b/.local/bin/prj
@@ -1,10 +1,15 @@
 #!/usr/bin/env bash
 
-pushd ~/Desktop/project/
+pushd ~/Desktop/project/ > /dev/null
 
 dir=$(ls -A | grep $1)
 dirLength=$(echo "$dir" | wc -w)
 counter=0
+
+if [[ -z $dir ]];then
+  echo "Direcotry dose not found!"
+  exit 1
+fi
 
 if [[ dirLength -ge 2 ]];then 
   for item in $dir ;do
@@ -17,5 +22,5 @@ else
   targetDir=$dir
 fi
 
-pushd $targetDir && lvim .
+pushd $targetDir > /dev/null && lvim .
 
